@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiYnJldHRAZW1haWwuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYifSwiaWF0IjoxNjI3NjgwMDg1LCJleHAiOjE2Mjc2ODM2ODV9.Xxco_EPogAy3zdwlq3lo-Pcx_uyIsIdPAKJQK4R1P8M
@id = 3

### POST NEW USER
POST {{url}}/user
Content-Type: application/json

{
  "displayName": "Brett Wiltshire",
  "email": "brett@email.com",
  "password": "123456",
  "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png"
}

### LOGIN
POST {{url}}/login
Content-Type: application/json

{
  "email": "brett@email.com",
  "password": "123456"
}

### GET ALL
GET {{url}}/user
Authorization: {{token}}

### GET BY ID
GET {{url}}/user/{{id}}
Authorization: {{token}}

### GET CATEGORIES
GET {{url}}/categories
Authorization: {{token}}

### POST A NEW BLOG POST
POST {{url}}/post
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Latest updates",
  "content": "Very newsi news",
  "categoryIds": [1]
}

### GET ALL BLOG POSTS
GET {{url}}/post
Authorization: {{token}}

### GET BLOG POST BY ID
GET {{url}}/post/5
Authorization: {{token}}
