@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoibGV3aXNoYW1pbHRvbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1NiJ9LCJpYXQiOjE2Mjc3NjExMDIsImV4cCI6MTYyNzc2NDcwMn0.Ro9IEdh9nbd7RCcKnk8yXN4MEFAGaoRumweuq1jU2eM
@id = 3

### POST NEW USER
POST {{url}}/user
Content-Type: application/json

{
  "displayName": "Brett Wiltshire",
  "email": "brett@email.com",
  "password": "123456",
  "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png"
}

### LOGIN
POST {{url}}/login
Content-Type: application/json

{
  "email": "lewishamilton@gmail.com",
  "password": "123456"
}

### GET ALL
GET {{url}}/user
Authorization: {{token}}

### GET BY ID
GET {{url}}/user/{{id}}
Authorization: {{token}}

### GET CATEGORIES
GET {{url}}/categories
Authorization: {{token}}

### POST A NEW BLOG POST
POST {{url}}/post
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Latest updates",
  "content": "Very newsi news",
  "categoryIds": [1]
}

### GET ALL BLOG POSTS
GET {{url}}/post
Authorization: {{token}}

### GET BLOG POST BY ID
GET {{url}}/post/1
Authorization: {{token}}

### PUT BLOG POST
PUT {{url}}/post/1
Authorization: {{token}}
Content-Type: application/json

{
  "title": "new title",
  "content": "new content"
}

###
GET {{url}}/post/search?q=
Authorization: {{token}}
