const STATUS_OK = 200;
const STATUS_CREATED = 201;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const CONFLICT = 409;
const INVALID_DATA = 422;
const SERVER_ERROR = 500;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  CONFLICT,
  INVALID_DATA,
  SERVER_ERROR,
};