const HTTP_BADREQ_STATUS = 400;
const HTTP_CREATED_STATUS = 201;
const HTTP_OK_STATUS = 200;
const HTTP_NOTFOUND_STATUS = 404;
const HTTP_NOCONTENT_STATUS = 204;
const HTTP_CONFLIT_STATUS = 409;
const HTTP_UNAUTHORIZED_STATUS = 401;
const HTTP_ERROR_STATUS = 500;

module.exports = {
  HTTP_BADREQ_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_OK_STATUS,
  HTTP_NOTFOUND_STATUS,
  HTTP_NOCONTENT_STATUS,
  HTTP_CONFLIT_STATUS,
  HTTP_UNAUTHORIZED_STATUS,
  HTTP_ERROR_STATUS,
 };