const OK_STATUS = 200;
const NO_CONTENT_STATUS = 204;
const CREATED_STATUS = 201;
const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED_STATUS = 401;
const FORBIDDEN_STATUS = 403;
const NOT_FOUND_STATUS = 404;
const CONFLICT_STATUS = 409;
const INTERNAL_ERROR_STATUS = 500;

module.exports = {
    OK_STATUS,
    NO_CONTENT_STATUS,
    CREATED_STATUS,
    BAD_REQUEST_STATUS,
    UNAUTHORIZED_STATUS,
    FORBIDDEN_STATUS,
    NOT_FOUND_STATUS,
    CONFLICT_STATUS,
    INTERNAL_ERROR_STATUS,
};